language: php

php: 7.1

before_script:
  - cp .env.travis .env
  - sudo service mysql start
  - mysql -e 'create database if not exists work_tracker;'
  - travis_retry composer self-update
  - travis_retry composer install --no-scripts --no-interaction
  - travis_retry composer update --no-scripts --no-interaction

script: ./bin/phpunit
