  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: work-tracker-api
    labels:
      app: work-tracker-api
  spec:
    selector:
      matchLabels:
        app: work-tracker-api
        tier: work-tracker
    replicas: 1
    template:
      metadata:
        labels:
          app: work-tracker-api
          tier: work-tracker
      spec:
        containers:
          - name: work-tracker-api
            image: rickynroses87/work-tracker-api
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
            env:
              - name: GET_HOSTS_FROM
                value: dns
                # Using `GET_HOSTS_FROM=dns` requires your cluster to
                # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
                # service launched automatically. However, if the cluster you are using
                # does not have a built-in DNS service, you can instead
                # access an environment variable to find the master
                # service's host. To do so, comment out the 'value: dns' line above, and
                # uncomment the line below:
                # value: env
            ports:
              - containerPort: 80
